services:
  - type: web
    name: instagram-app
    runtime: static
    rootDir: Instagram
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
